# ALLOWS TO CONFIGURE MESSAGES

config-message:
  enable: "Plugin enabled !"
  disable: "Plugin disabled!"
  global-messages:
    - "§a» your message !"
    - "§a» made by xilapmpl !"

# ALLOWS TO CONFIGURE THE SETTINGS

config-settings:
  interval-message: 120
  type: "message" #(message | popup | toast)
